### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by MSusik** [oyvble/euroformix#11]
Hi!

I noticed the repo has no licence associated. I believe the project is intended to be open-source, and therefore this might be an issue.

According to [this thread on StackOverflow](https://opensource.stackexchange.com/a/1721) the software can not be used unless a private licence is granted to the users. To fix this, an open source licence should be added to the repo. Given the lack of a license I am actually not allowed modify the code to add a licence and create a pull request :). Therefore I would kindly ask you to add one. For a review of available options please see https://choosealicense.com/

**Comment by oyvble** [comment]
Thanks for making me aware of this issue. I have included a file with the GNU GLPv3 licence.
