### ISSUE TITLE
Should allele frequencies add to 1?

### ISSUE THREAD

**Issue by thoree** [oyvble/euroformix#2]
I am missing an error message below:

``` r
library(euroformix, quietly = T)
freq = list("L1" = c("1" = 0.9, "2" = 1.1))
genDataset(2, freq, mx = c(0.8, 0.2))[[2]][[1]]
#> $L1
#> $L1$adata
#> [1] "2"
#> 
#> $L1$hdata
#> [1] 1965
```

<sup>Created on 2019-12-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by oyvble** [comment]
I suggest to add this to the genDataset function (next release):

  isNotSimplex = function(x) { #helpfunction of consider being simplex
	return( sum(x)!=1 || any(x < 0 | x > 1) )
  }
  if( any( sapply(popFreq,isNotSimplex) ) ) stop("Some of the frequency elements  was not a simplex")

**Comment by thoree** [comment]
Possibly sum(x)!=1 could run into problems. What about
round(sum(x),6) == 1

**Comment by oyvble** [comment]
Yes indeed that could cause some problems: 
I will replace
```R
 sum(x)!=1
```
with
```R
round(sum(x),6)!=1
```

**Comment by oyvble** [comment]
This issue has already been resolved. I suggest printing or warning, followed by a rescaling of the frequencies.
From v3.3.0 a warning will be throwed (instead of printing).
